version: "3.7"
services:

  app:
    build:
      args:
        user: forif
        uid: 1000
      context: ./
      dockerfile: .dockerfile
    image: hurtado
    container_name: hurtado-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - hurtado

  db:
    image: mysql:5.7
    container_name: hurtado-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - hurtado

  nginx:
    image: nginx:1.17-alpine
    container_name: hurtado-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - hurtado

networks:
  hurtado:
    driver: bridge